import { PartModel } from '@/types';

export const INITIAL_SAMPLE_DATA: PartModel[] = [
  {
    id: 'sample-1',
    partNumber: 'ENG-2041-A',
    vehicleModel: 'ヤリス (Yaris)',
    lines: ['Line 1', 'Line 2', 'Line 5'],
    notes: '高圧インジェクター対応 / メインライン',
    status: 'active',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
  },
  {
    id: 'sample-2',
    partNumber: 'ENG-2041-B',
    vehicleModel: 'ヤリス クロス (Yaris Cross)',
    lines: ['Line 1', 'Line 6', 'Line 11'],
    notes: '4WD用仕様 / 治具交換要',
    status: 'active',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 28).toISOString(),
  },
  {
    id: 'sample-3',
    partNumber: 'ELE-8802-K',
    vehicleModel: 'プリウス (Prius)',
    lines: ['Line 2', 'Line 3', 'Line 12', 'Line 15'],
    notes: 'HEV標準電装ユニット / 4ライン流動可',
    status: 'active',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
  },
  {
    id: 'sample-4',
    partNumber: 'CHA-1090-X',
    vehicleModel: 'クラウン (Crown)',
    lines: ['Line 7', 'Line 14'],
    notes: '大型フレーム用ライン',
    status: 'active',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
  },
  {
    id: 'sample-5',
    partNumber: 'CHA-1090-Y',
    vehicleModel: 'クラウン スポーツ (Crown Sport)',
    lines: ['Line 7', 'Line 8', 'Line 14', 'Line 16'],
    notes: 'スポーツサス対応 / 4ライン対応',
    status: 'active',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
  },
  {
    id: 'sample-6',
    partNumber: 'INT-3310-F',
    vehicleModel: 'カローラ (Corolla)',
    lines: ['Line 3', 'Line 4', 'Line 13'],
    notes: '10インチナビ仕様',
    status: 'active',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
  },
  {
    id: 'sample-7',
    partNumber: 'DRV-7700-Z',
    vehicleModel: 'ランドクルーザー250 (Land Cruiser 250)',
    lines: ['Line 17'],
    notes: '超重量物専用17ライン限定 / 試作評価中',
    status: 'trial',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: 'sample-8',
    partNumber: 'SEN-5011-S',
    vehicleModel: 'プリウス (Prius)',
    lines: ['Line 2', 'Line 4', 'Line 11', 'Line 12'],
    notes: 'ミリ波レーダーユニット',
    status: 'active',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: 'sample-9',
    partNumber: 'BOD-6003-M',
    vehicleModel: 'アルファード (Alphard)',
    lines: ['Line 5', 'Line 8', 'Line 15'],
    notes: '電動スライドドア関連',
    status: 'active',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: 'sample-10',
    partNumber: 'BAT-9900-H',
    vehicleModel: 'bZ4X (BEV)',
    lines: ['Line 6', 'Line 16', 'Line 17'],
    notes: 'BEV専用バッテリーパックマウント',
    status: 'active',
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  }
];
